-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "old_price" DROP NOT NULL,
ALTER COLUMN "sellable_online" DROP NOT NULL,
ALTER COLUMN "link" DROP NOT NULL,
ALTER COLUMN "other_colors" DROP NOT NULL,
ALTER COLUMN "designer" DROP NOT NULL,
ALTER COLUMN "depth" DROP NOT NULL,
ALTER COLUMN "height" DROP NOT NULL,
ALTER COLUMN "width" DROP NOT NULL;
