import { hashSync } from "bcrypt-ts-edge";

const ikeaProducts = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: hashSync("123456", 10),
      role: "admin",
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: hashSync("123456", 10),
      role: "user",
    },
  ],

  products: [
    {
      item_id: "19011777",
      name: "MELLTORP",
      category: "Tables & desks",
      price: 199.0,
      old_price: "SR 250",
      sellable_online: true,
      link: "https://www.ikea.com/sa/en/p/melltorp-table-white-s19011777/",
      other_colors: "No",
      description: "Table,          125x75 cm",
      designer: "Lisa Norinder",
      depth: 10,
      height: 74,
      width: 75,
      stock: 37,
      slug: "MELLTORP",
      rating: 3.2,
      numReviews: 502,
      isFeatured: false,
      banner: "",
      images: [
        "/images/sample-products/melltorp-table-white__0737266_pe740964_s5.avif",
      ],
      brand: "Ikea",
    },
    {
      item_id: "70466496",
      name: "LJUV",
      category: "Tables & desks",
      price: 245.0,
      old_price: "No old price",
      sellable_online: true,
      link: "https://www.ikea.com/sa/en/p/ljuv-coffee-table-hexagonal-gold-colour-pink-70466496/",
      other_colors: "No",
      description: "Coffee table,          60x52 cm",
      designer: "Nada Debs",
      depth: 10,
      height: 28,
      width: 52,
      images: [
        "/images/sample-products/ljuv-table-plateau-couleur-or-noir.avif",
        "/images/sample-products/lljuv-table-plateau-couleur-or-noir2.avif",
        "/images/sample-products/lljuv-table-plateau-couleur-or-noir3.avif",
      ],
      stock: 82,
      slug: "LJUV",
      rating: 2.6,
      numReviews: 276,
      isFeatured: true,
      banner: "",
      brand: "Ikea",
    },
    {
      item_id: "60214159",
      name: "MALM",
      category: "Tables & desks",
      price: 475.0,
      old_price: "SR 545",
      sellable_online: true,
      link: "https://www.ikea.com/sa/en/p/malm-desk-white-60214159/",
      other_colors: "Yes",
      description: "Desk,          140x65 cm",
      designer:
        "602.141.59 You can collect cables and extension leads on the shelf under the table top, so they’re hidden but still close at hand.Can be placed in the middle of a room because the back is finished.You can mount the storage unit to the right or left, according to your space or preference. Combines with other furniture in the MALM series.May be completed with SUMMERA drawer insert with 6 compartments to create order in the drawer.",
      depth: 65,
      height: 73,
      width: 140,
      images: [
        "/images/sample-products/malm-desk-white1.avif",
        "/images/sample-products/malm-desk-white2.avif",
        "/images/sample-products/malm-desk-white3.avif",
      ],
      stock: 18,
      slug: "MALM",
      rating: 3.5,
      numReviews: 800,
      isFeatured: true,
      banner: "",
      brand: "Ikea",
    },
    {
      item_id: "49011766",
      name: "MELLTORP / ADDE",
      category: "Tables & desks",
      price: 179.0,
      old_price: "SR 205",
      sellable_online: true,
      link: "https://www.ikea.com/sa/en/p/melltorp-adde-table-and-2-chairs-white-s49011766/",
      other_colors: "No",
      description: "Table and 2 chairs,          75 cm",
      designer: "Lisa Norinder/Marcus Arvonen",
      depth: 10,
      height: 72,
      width: 75,
      images: [
        "/images/sample-products/melltorp-genesoen-table-and-2-chairs-white-white-metal-blue1.jpg",
        "/images/sample-products/melltorp-genesoen-table-and-2-chairs-white-white-metal-blue2.avif",
        "/images/sample-products/melltorp-genesoen-table-and-2-chairs-white-white-metal-blue3.avif",
        "/images/sample-products/melltorp-genesoen-table-and-2-chairs-white-white-metal-blue4.avif",
      ],
      stock: 17,
      slug: "MELLTORP-ADDE",
      rating: 2.7,
      numReviews: 34,
      isFeatured: false,
      banner: "",
      brand: "Ikea",
    },
    {
      item_id: "59133593",
      name: "LINNMON / ADILS",
      category: "Tables & desks",
      price: 270.0,
      old_price: "SR 315",
      sellable_online: true,
      link: "https://www.ikea.com/sa/en/p/linnmon-adils-corner-table-black-brown-blue-s59133593/",
      other_colors: "Yes",
      description: "Corner table,          120x120 cm",
      designer: "Jon Karlsson",
      depth: 10,
      height: 74,
      width: 120,
      images: [
        "/images/sample-products/linnmon-adils-desk-black-brown-white_1.avif",
        "/images/sample-products/linnmon-adils-desk-black-brown-white_2.avif",
      ],
      stock: 79,
      slug: "LINNMON-ADILS",
      rating: 2.2,
      numReviews: 187,
      isFeatured: false,
      banner: "",
      brand: "Ikea",
    },
    {
      item_id: "19216694",
      name: "SKÅDIS",
      category: "Tables & desks",
      price: 80.0,
      old_price: "SR 90",
      sellable_online: true,
      link: "https://www.ikea.com/sa/en/p/skadis-pegboard-combination-white-s19216694/",
      other_colors: "No",
      description: "Pegboard combination,          36x56 cm",
      designer: "Eva Lilja Löwenhielm",
      depth: 12,
      height: 56,
      width: 36,
      images: [
        "/images/sample-products/skadis-pegboard-combination__1.avif",
        "/images/sample-products/skadis-pegboard-combination__2.avif",
      ],
      stock: 38,
      slug: "SKADIS",
      rating: 1.6,
      numReviews: 164,
      isFeatured: true,
      banner: "",
      brand: "Ikea",
    },
    {
      item_id: "50411990",
      name: "GLADOM",
      category: "Tables & desks",
      price: 59.0,
      old_price: "No old price",
      sellable_online: true,
      link: "https://www.ikea.com/sa/en/p/gladom-tray-table-black-50411990/",
      other_colors: "Yes",
      description: "Tray table,          45x53 cm",
      designer: "Chenyi Ke",
      depth: 10,
      height: 53,
      width: 0,
      images: [
        "/images/sample-products/gladom-tray-table-black__1.avif",
        "/images/sample-products/gladom-tray-table-black__2.avif",
        "/images/sample-products/gladom-tray-table-black__3.avif",
      ],
      stock: 57,
      slug: "GLADOM",
      rating: 1.5,
      numReviews: 45,
      isFeatured: true,
      banner: "",
      brand: "Ikea",
    },
    {
      item_id: "80213074",
      name: "MICKE",
      category: "Tables & desks",
      price: 276.0,
      old_price: "SR 345",
      sellable_online: true,
      link: "https://www.ikea.com/sa/en/p/micke-desk-white-80213074/",
      other_colors: "Yes",
      description: "Desk,          105x50 cm",
      designer: "Henrik Preutz",
      depth: 50,
      height: 75,
      width: 105,
      images: [
        "/images/sample-products/micke-desk-white-anthracite__1.avif",
        "/images/sample-products/micke-desk-white-anthracite__2.avif",
        "/images/sample-products/micke-desk-white-anthracite__3.avif",
      ],
      stock: 39,
      slug: "MICKE",
      rating: 3.6,
      numReviews: 836,
      isFeatured: false,
      banner: "",
      brand: "Ikea",
    },
    {
      item_id: "90449905",
      name: "LACK",
      category: "Tables & desks",
      price: 89.0,
      old_price: "No old price",
      sellable_online: true,
      link: "https://www.ikea.com/sa/en/p/lack-coffee-table-white-90449905/",
      other_colors: "Yes",
      description: "Coffee table,          90x55 cm",
      designer: "IKEA of Sweden",
      depth: 10,
      height: 45,
      width: 55,
      images: [
        "/images/sample-products/lack-side-table-white-stained-oak-effect__1.avif",
        "/images/sample-products/lack-side-table-white-stained-oak-effect__2.avif",
        "/images/sample-products/lack-side-table-white-stained-oak-effect__3.avif",
      ],
      stock: 69,
      slug: "LACK",
      rating: 2.0,
      numReviews: 535,
      isFeatured: false,
      banner: "",
      brand: "Ikea",
    },
  ],
};

export default ikeaProducts;
